development: &base
        root: "/var/cloud"
        instance_root: "/var/cloud/instances"
        disk_root: "/var/cloud/disks"
        template_root: "/var/cloud/templates"
test:
        <<: *base
production:
        <<: *base
