development: &base
        xl: "/usr/sbin/xl"
        xenstore-read: "/usr/bin/xenstore-read"
        xenstore-ls: "/usr/bin/xenstore-ls"
        vhd-util: "/usr/sbin/vhd-util"
        tap-ctl: "/usr/sbin/tap-ctl"
test:
        <<: *base
production:
        <<: *base
