#!/bin/sh
#
# xenperfd    	Script to start and stop xenperf
#
# Author:       Taekmin Kim <tantara@wafflestudio.com>
#
# chkconfig: 2345 99 00
# description: Starts and stops xenstored and xenconsoled
### BEGIN INIT INFO
# Provides:          xenperfd
# Required-Start:    $syslog $remote_fs xenstored xenconsoled
# Should-Start:
# Required-Stop:     $syslog $remote_fs xenstored xenconsoled
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop xenperf
# Description:       Starts and stops the daemons neeeded for xenperf
### END INIT INFO

NAME=xenperf
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

op_start()
{
	echo "Starting xenperf daemon"
	$NAME &
}

op_stop()
{
	kill `cat $PIDFILE`
	rm -f $PIDFILE
	echo "Stopped xenperf daemon"
}

case "$1" in
	start)
	[ -f $PIDFILE ] && exit 1 || op_start
	;;
	stop)
	op_stop
	;;
	status)
	if [ -f $PIDFILE ]; then
		echo "Running"
	else
		echo "Stopped"
	fi
	;;
	restart)
	op_stop
	sleep 1
	op_start
	;;
	*)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
	exit 3
	;;
esac
